export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const LOAD_COLOR_CODES_SUCCESS = 'LOAD_COLOR_CODES_SUCCESS';
export const SAVE_CALCULATOR_SUCCESS = 'SAVE_CALCULATOR_SUCCESS';
export const CALCULATE_CALCULATOR_SUCCESS = 'CALCULATE_CALCULATOR_SUCCESS';